const char *cabecera =
"<!doctype html>\n"
"<html>\n"
"<meta name=\"viewport\"\n"
"content=\"user-scalable=yes, width=device-width, target-densityDpi=device-dpi, initial-scale=1.0\" />\n"
"<head>\n"
"   <title>MONKI</title>\n"
"</head>\n"
"<body>\n"
"<table align=\"center\" border=\"0\" cellpadding=\"1\" cellspacing=\"2\"\n"
"       style=\"height:100%;width:100%;\" summary=\"Page\">\n"
"   <tbody>\n"
"      <tr>\n"
"         <td style=\"text-align: center; background-color: rgb(0, 0, 0);\">\n"
"            <strong>\n"
"               <span style=\"font-family:lucida sans unicode,lucida grande,sans-serif;\">\n"
"               <span style=\"color: rgb(255, 255, 255);\">\n"
"                  PADS\n"
"               </span>\n"
"               </span>\n"
"            </strong>\n"
"         </td>\n"
"      </tr>\n"
"      <tr>\n"
"         <td style=\"text-align: left; vertical-align: middle;\n"
"                     background-color: rgb(255, 255, 204);\">\n"
"            <form action=\"start\">\n"
"               <input type=\"submit\" value=\"Start\">\n"
"            </form>\n"
"            <form action=\"pause\">\n"
"               <input type=\"submit\" value=\"Pause\">\n"
"            </form>\n"
"            <form action=\"stop\">\n"
"               <input type=\"submit\" value=\"Stop\">\n"
"            </form>\n"
"            <form action=\"resume\">\n"
"               <input type=\"submit\" value=\"Resume\">\n"
"            </form>\n"
"            <form action=\"file\">\n"
"               <input type=\"submit\" value=\"Xfer file\">\n"
"            </form>\n"
"            <form action=\"data.txt\">\n"
"               <input type=\"submit\" value=\"Get file\">\n"
"            </form>\n"
"         </td>\n"
"      </tr>\n"
"      <tr>\n"
"         <td style=\"text-align: left; background-color: rgb(100, 100, 100);\">\n"
"            <span style=\"color: rgb(230, 130, 130);\">\n"
"            <span style=\"font-family: lucida sans unicode,lucida grande,sans-serif;\">\n";

const char *cola =
"            </span>\n"
"            </span>\n"
"         </td>\n"
"      </tr>\n"
"   </tbody>\n"
"</table>\n"
"</body>\n"
"</html>\n";

